spring:
  application:
    name: "minD-backend"
  datasource:
    url: jdbc:postgresql://192.168.0.108:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

rate-limiter:
  max-requests: 50
  time-window: 60